FROM jenkins/jenkins:lts-jdk17

USER root

# Update system and install prerequisites
RUN apt-get update && \
    apt-get install -y ca-certificates curl

# Install Docker using the secure method
RUN install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc && \
    chmod a+r /etc/apt/keyrings/docker.asc && \
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bullseye stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin && \
    apt-get clean

# Add jenkins user to docker group
RUN usermod -aG docker jenkins

USER jenkins